[package]
name = "workshop"
version = "0.1.0"
authors = ["Sebastian DrÃ¶ge <sebastian@centricular.com>", "Guillaume Gomez <guillaume1.gomez@gmail.com>"]

[dependencies]
glib = "0.6"
gio = "0.5"
gtk = { version = "0.5", features = ["v3_10"] }
gstreamer = "0.12"
fragile = "0.3"
serde = "^1"
serde_any = "0.5"