[package]
name = "workshop"
version = "0.1.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>", "Guillaume Gomez <guillaume1.gomez@gmail.com>"]

[dependencies]
gtk = { version = "0.5", features = ["v3_6"] }
gio = "0.5"
